### ISSUE TITLE
Unnecessary truncation

### ISSUE THREAD

**Issue by jtgd** [syui/twg#1]
I notice in comparing the output of twg with the actual Twitter page that you truncate the texts at 140 chars, adding an ellipsis. Now that Twitter has expanded the maximum tweet to 280 characters it seems you can remove, or expand, that truncation.

**Comment by syui** [comment]
I see, thanks.

I use `tweet.Full.Text`, but have the problem been improved?

[https://github.com/ChimeraCoder/anaconda/pull/200](https://github.com/ChimeraCoder/anaconda/pull/200)

**Comment by syui** [comment]
fix : 204227ce2e67c58f4e720180f686a481e18ee22e

**Comment by jtgd** [comment]
Fix confirmed. Thank you!

**Comment by jtgd** [comment]
The truncation still occurs with retweets.

**Comment by syui** [comment]
Thank you very much.

I will see it when I have time.

**Comment by syui** [comment]
fix layout 7c381cdfade1550a4756d5b76305053f88980508

```sh
$ twg set f
$ twg t
```

**Comment by jtgd** [comment]
$ aurman -Syu
  
:: The following 1 package(s) are getting updated:
   aur/twg  0.1-1  ->  0.2-1

?? Do you want to continue? Y/n:
~~ looking for new pkgbuilds and fetching them...
==> Making package: twg 0.2-1 (Wed Jun 13 10:33:08 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found linux_386_twg
  -> Found linux_amd64_twg
==> Validating source files with sha1sums...
    linux_386_twg ... FAILED
    linux_amd64_twg ... FAILED
==> ERROR: One or more files did not pass the validity check!
2018-06-13 10:33:08,263 - wrappers - makepkg - ERROR - makepkg query makepkg -cf --noconfirm failed in directory /home/jay/.cache/aurman/twg

$ curl -SLO https://github.com/syui/twg/releases/download/0.2/linux_amd64_twg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   606    0   606    0     0   1020      0 --:--:-- --:--:-- --:--:--  1018
100 14.1M  100 14.1M    0     0  4003k      0  0:00:03  0:00:03 --:--:-- 6725k

$ chmod +x linux_amd64_twg

$ sudo mv linux_amd64_twg /usr/bin/twg

$ twg -v
twg version 0.2.8

$ twg u @johnfugelsang
JohnFugelsang Tomorrow night I'm hosting "The White People Show" for Comedy Nation at @WESTSIDECCNYC.  Come get your Caucasian on with @RhondaHansome @maysoonzayid @KerbyDarius @MehranX in standup &amp; panel form.   Not to be missed. https://t.co/aDuqzCSPHy
JohnFugelsang RT @SXMInsight: New to @SIRIUSXM or have a friend who doesn't listen? We have an offer for you! Go to https://t.co/bwUbqKxfAp for Offer Det…
JohnFugelsang It’s not that some people think denuclearization of NK because of this deal is a bad thing, it’s that some people think denuclearization of NK because of this deal is an actual thing.


$ twg t
TheGoodGodAbove RT @barbara_guraj After almost 3 years of battling with immigration, my mom was finally allowed to come back to America. She arrived today and surprised my brother, who was 7 when she left, and this was his reaction. https://t.co/DoVoNHRZHn

$ twg u @thegoodgodabove
TheGoodGodAbove RT @barbara_guraj: After almost 3 years of battling with immigration, my mom was finally allowed to come back to America. She arrived today…

Note that I can't install through normal channels.

Notice how only the line with "RT" is truncated.

Notice how it is different for timeline and for individual user.

**Comment by syui** [comment]
## aur package error 

I am sorry, I have not confirmed aur package.

## twg user

```sh
$ twg u
```

I was aware of the difference.

I judged that the use frequency of the user search timeline is low.

I was afraid that everything would be a complicated code.

However, it would be better to modify it.

**Comment by syui** [comment]
update : 72d385afd6b3cd1bbb35a7e01d03a3336fa689fd

**Comment by syui** [comment]
Add new function.

```sh
$ twg u syui__ 3
tweet 1
tweet 2
tweet 3
```

**Comment by jtgd** [comment]
Looks like you fixed it. Thanks. 

Sorry for the trouble, I guess my use-case is rather different. I don't tweet but treat Twitter like a news feed. I have a system of reading RSS feeds inside Emacs org-mode and I thought it would be nice to add Twitter in there too. That's why I like to keep the "feeds" separate. I suppose I could parse the timeline output and match on the leading string to demultiplex them, but found that you had conveniently provided that feature with the "u". :)
