### ISSUE TITLE
panic: certificate signed by unknown authority

### ISSUE THREAD

**Issue by focusaurus** [syui/twg#2]
Getting this error trying to post a tweet:

```
panic: Post "https://api.twitter.com/1.1/statuses/update.json": x509: certificate signed by unknown authority
```

OS Details: macOS Catalina 10.15.7 (19H1217)

Maybe the CA database from either macos or golang built-in needs an update? Maybe a rebuild on a current golang would do it? I can try rebuilding and will report my findings.

**Comment by syui** [comment]
thank you for the report.
Are you using the release version?
The release version includes the key given by twitter and builds it.
If you are not using the release version and you want to build and use it, please prepare the config.json file: twg/config.json
You can get the client app key from twitter and try to build it.

**Comment by focusaurus** [comment]
I'm using the release 0.3.1 `twg version 0.3.1`.

**Comment by focusaurus** [comment]
I'm having a hard time getting this to work on macos. I built from source with my credentials embedded (aside: this is insecure as they are not encrypted nor kept secure with filesystem permissions)

```
go build -ldflags="-X github.com/syui/twg/oauth.ckey=$(jq -r .consumer_key config.json) -X github.com/syui/twg/oauth.cskey=$(jq -r .consumer_secret config.json)"
```

I get 401 even though my consumer key and consumer secret are embedded in the executable correctly.

```
./twg o
2021/07/03 09:13:05 getBody: httpExecute: HTTP response is not 200/OK as expected. Actual response:
        Response Status: '401 Unauthorized'
        Response Code: 401
        Response Body: {"errors":[{"code":32,"message":"Could not authenticate you."}]}
        Request Headers: [key: Authorization, val: OAuth oauth_callback="oob",oauth_consumer_key="REDACTED_BUT_IS_CORRECT",oauth_nonce="2395503072442143632",oauth_signature="8jVz4bgPIQ18wH7fFtAkGtR2JTI%3D",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1625325185",oauth_version="1.0"]
```

**Comment by focusaurus** [comment]
OK I eventually got this working by going through the full dance of registering a developer account, creating an app, creating a key with write access, doing oauth on the command line, etc, and now I can post again!

**Comment by syui** [comment]
Thanks for the report.
It is strange that releases does not work, so it is possible that it is broken.
However, it seems to be working on my mac, so I'm a bit confused about the cause.
twg works by placing the user file in `.config/twg/user.json`.

```json
{"Token":"","Secret":"","AdditionalData":{"screen_name":"syui__","user_id":"106954056"}}
```

**Comment by syui** [comment]
Congratulations on registering the app!
